create table Users(
    id int generated by default as identity primary key,
    username varchar(100) not null unique,
    password varchar(100) not null,
    email varchar(100) not null,
    role varchar(50) not null
);

create table Note(
    id int generated by default as identity,
    user_id int references users(id) on delete cascade,
    amount numeric(10,2) not null,
    category varchar(100) not null,
    description varchar(255),
    transaction_date timestamp not null
);
